<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OmsiCompat.Map/OmsiCompat.Map.csproj" />
    <ProjectReference Include="../OmsiCompat.Models/OmsiCompat.Models.csproj" />
    <ProjectReference Include="../OmsiCompat.Scenery/OmsiCompat.Scenery.csproj" />
    <ProjectReference Include="../OmsiCompat.Splines/OmsiCompat.Splines.csproj" />
  </ItemGroup>
</Project>
