<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OMSICompatible.Renderer.Common/OMSICompatible.Renderer.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
  </ItemGroup>
</Project>
